Repository ministryofjustice/prison-visits-2, pull requests merged in 2018-04, with the labels that each got.

#1566 Wrap Raven.capture_exception
  Gemfile
  app/middleware/error_handler.rb
  app/services/nomis/api.rb
  app/services/nomis/client.rb
  app/services/prisoner_location_validation.rb
  app/services/sendgrid_api.rb
  config/initializers/pvb_exception.rb
  config/initializers/raven.rb
  lib/pvb/exception_handler.rb
  spec/controllers/api/validations_controller_spec.rb
  spec/controllers/application_controller_spec.rb
  spec/features/process_a_request_accept_with_contact_list_spec.rb
  spec/features/process_a_request_cancel_spec.rb
  spec/features/process_a_request_nomis_disabled_spec.rb
  spec/features/process_a_request_reject_spec.rb
  spec/features/process_a_request_unprocessable_spec.rb
  spec/middleware/error_handler_spec.rb
  spec/presenters/prisoner_location_presenter_spec.rb
  spec/pvb/exception_handler_spec.rb
  spec/rails_helper.rb
  spec/services/api_prisoner_checker_spec.rb
  spec/services/nomis/api_spec.rb
  spec/services/nomis/client_spec.rb
  spec/services/sendgrid_api/shared_examples.rb
Labels: Ready For Merge, review me

#1583 Format date selection display
  app/assets/stylesheets/_buttons.scss
  app/decorators/concrete_slot_decorator.rb
  app/helpers/date_helper.rb
  app/views/prison/visits/_visit_date_section.html.erb
  config/initializers/date_formats.rb
  spec/decorators/concrete_slot_decorator_spec.rb
Labels: review me

#1587 Risley slot updates
  db/seeds/prisons/RSI-risley.yml
Labels: Ready For Merge, review me, slot updates

#1586 Wymott slot updates
  db/seeds/prisons/WMI-wymott.yml
Labels: Ready For Merge, review me, slot updates

#1565 Display slot information
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/moj.GAEvent.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/modules/_slot-list.scss
  app/controllers/staff_info_controller.rb
  app/decorators/day_decorator.rb
  app/decorators/prison_decorator.rb
  app/decorators/slot_info_decorator.rb
  app/presenters/slot_info_presenter.rb
  app/views/days/_day.erb
  app/views/prisons/_prison.erb
  app/views/staff_info/_no_visits.erb
  app/views/staff_info/_slot_list_item.erb
  app/views/staff_info/show.html.erb
  config/locales/en/prison_views.yml
  spec/controllers/staff_info_controller_spec.rb
  spec/decorators/prison_decorator_spec.rb
  spec/decorators/slot_info_decorator_spec.rb
  spec/features/slot_update_spec.rb
  spec/presenters/slot_info_presenter_spec.rb
Labels: Do Not Merge, in progress, review me

#1597 Liverpool Social visit slot updates
  db/seeds/prisons/LPI-liverpool-social-visits.yml
Labels: Ready For Merge, review me, slot updates

#1602 Whitemoor visit slots change to 1345-1605
  db/seeds/prisons/WRI-whitemoor.yml
Labels: Ready For Merge, review me, slot updates

#1611 Hull visit slots updates
  db/seeds/prisons/HLI-hull.yml
Labels: Ready For Merge, review me, slot updates

#1615 Wormwood Scrubs family day
  db/seeds/prisons/WSI-wormwood-scrubs.yml
Labels: Ready For Merge, review me, slot updates

#1622 Haverigg unbookable dates
  db/seeds/prisons/HVI-haverigg.yml
Labels: Ready For Merge, review me, slot updates

#1637 Update Chelmsford weekday slot times
  db/seeds/prisons/CDI-chelmsford.yml
Labels: Ready For Merge, review me, slot updates
