Repository ministryofjustice/prison-visits-2, pull requests merged in 2018-06, with the labels that each got.

#1704 Add logging for Zendesk clean up task
  lib/tasks/zendesk_cleanup.rake
Labels: in progress

#1705 Correction to zendesk api call
  app/services/zendesk/pvb_api.rb
  spec/services/zendesk/pvb_api_spec.rb
Labels: in progress

#1708 Update NWI-norwich-britannia-house.yml
  db/seeds/prisons/NWI-norwich-britannia-house.yml
Labels: in progress

#1712 Wymott unbookable dates
  db/seeds/prisons/WMI-wymott.yml
Labels: Ready For Merge, in progress, review me, slot updates

#1716 Fix offender details when API returns an empty field
  app/services/nomis/offender.rb
  spec/services/nomis/offender_spec.rb
Labels: in progress

#1721 Belmarsh email address update
  db/seeds/prisons/BAI-belmarsh.yml
Labels: Ready For Merge, in progress, review me

#1715 Restrict print visits search to 6 months
  app/controllers/prison/print_visits_controller.rb
  app/models/print_visits.rb
  app/views/prison/print_visits/create.html.erb
  config/locales/en/errors.yml
  config/locales/en/prison_views.yml
  spec/features/print_visits_spec.rb
  spec/models/print_visits_spec.rb
Labels: Ready For Merge

#1722 Remove Highline gem
  Gemfile
  Gemfile.lock
Labels: review me

#1723 Send user stamp into nomis
  app/services/booking_responder/accept.rb
  app/services/create_nomis_visit.rb
  app/services/nomis/api.rb
  spec/services/booking_responder/accept_spec.rb
  spec/services/create_nomis_visit_spec.rb
  spec/services/nomis/api_spec.rb
Labels: in progress

#1714 Display visitor restrictions
  app/assets/javascripts/modules/moj.matchVisitors.js
  app/assets/stylesheets/modules/_visitor-list.scss
  app/services/book_to_nomis_config.rb
  app/services/nomis/feature.rb
  app/services/staff_nomis_checker.rb
  app/views/prison/visits/_visitor_contact.html.erb
  config/application.rb
  config/locales/en/prison_views.yml
  docs/configuration.md
  spec/features/cancel_booked_to_nomis_visit_spec.rb
  spec/features/process_a_request_accept_with_contact_list_spec.rb
  spec/features/process_a_request_nomis_disabled_spec.rb
  spec/features/process_a_request_reject_spec.rb
  spec/features/process_a_request_unprocessable_spec.rb
  spec/fixtures/vcr_cassettes/visitor_restriction_rejection.yml
  spec/services/book_to_nomis_config_spec.rb
  spec/services/nomis/feature_spec.rb
  spec/services/staff_nomis_checker_spec.rb
Labels: review me

#1733 Update Cardiff's visit slots
  db/seeds/prisons/CFI-cardiff.yml
Labels: Ready For Merge, review me, slot updates

#1745 Update phone numbers
  db/seeds/prisons/DWI-downview.yml
  db/seeds/prisons/ESI-east-sutton-park.yml
  db/seeds/prisons/EWI-eastwood-park.yml
  db/seeds/prisons/FHI-foston-hall.yml
  db/seeds/prisons/LNI-low-newton.yml
  db/seeds/prisons/NHI-new-hall.yml
  db/seeds/prisons/SDI-send.yml
  db/seeds/prisons/STI-styal.yml
  db/seeds/prisons/WSI-wormwood-scrubs.yml
  db/seeds/prisons/WWI-wandsworth.yml
Labels: review me

#1742 Maidstone unbookable dates August
  db/seeds/prisons/MSI-maidstone.yml
Labels: Ready For Merge, review me, slot updates
