Repository ministryofjustice/prison-visits-2, pull requests merged in 2018-03, with the labels that each got.

#1479 Chelmsford updates
  db/seeds/prisons/CDI-chelmsford.yml
Labels: Ready For Merge, review me, slot updates

#1480 Coldingley-slot-updates
  db/seeds/prisons/CLI-coldingley.yml
Labels: Ready For Merge, review me, slot updates

#1481 Moorland slot updates
  db/seeds/prisons/MDI-moorland-closed.yml
Labels: Ready For Merge, review me, slot updates

#1482 Maidstone slot updates
  db/seeds/prisons/MSI-maidstone.yml
Labels: Ready For Merge, review me, slot updates

#1499 Buckley-hall-slot-updates
  db/seeds/prisons/BCI-buckley-hall.yml
Labels: Ready For Merge, review me, slot updates

#1498 Update existing licence and link from README
  LICENSE
  README.md
Labels: review me

#1500 Wayland-slot-updates
  db/seeds/prisons/WLI-wayland.yml
Labels: Ready For Merge, review me, slot updates

#1501 Add Yann's README edits from earlier WIP PR
  README.md
Labels: review me

#1391 Use Ruby 2.5.0 **DO NOT MERGE**
  .circleci/config.yml
  Dockerfile
  Gemfile
  Gemfile.lock
Labels: Do Not Merge

#1504 Hull-slot-updates
  db/seeds/prisons/HLI-hull.yml
Labels: Ready For Merge, review me, slot updates

#1503 Update .ruby-version file (2.5.0). Delete duplicate LICENCE
  LICENCE
Labels: review me

#1507 Rochester slot updates
  db/seeds/prisons/RCI-rochester.yml
Labels: Ready For Merge, review me, slot updates

#1508 Wymott slot update
  db/seeds/prisons/WMI-wymott.yml
Labels: Ready For Merge, review me, slot updates

#1509 Feltham 18-21 slot update
  db/seeds/prisons/FMI-feltham-young-adults-18-21-only.yml
Labels: Ready For Merge, review me, slot updates

#1515 Exeter Easter slot update
  db/seeds/prisons/EXI-exeter.yml
Labels: Ready For Merge, review me, slot updates

#1517 Holme House slot updates
  db/seeds/prisons/HHI-holme-house.yml
Labels: Ready For Merge, review me, slot updates

#1516 North-sea-camp slot updates
  db/seeds/prisons/NSI-north-sea-camp.yml
Labels: Ready For Merge, review me, slot updates

#1485 Update the generic book to NOMIS error
  config/locales/en/prison_views.yml
  spec/controllers/prison/visits_controller_spec.rb
Labels: review me

#1520 Remove 'contact list' feature flag
  app/decorators/visit_decorator.rb
  app/services/book_to_nomis_config.rb
  app/services/nomis/feature.rb
  app/services/staff_nomis_checker.rb
  app/views/prison/visits/_visitor_contact.html.erb
  app/views/prison/visits/_visitor_details.html.erb
  config/application.rb
  spec/decorators/visit_decorator_spec.rb
  spec/features/cancel_booked_to_nomis_visit_spec.rb
  spec/features/process_a_request_accept_with_contact_list_spec.rb
  spec/features/process_a_request_accept_without_contact_list_spec.rb
  spec/features/process_a_request_cancel_spec.rb
  spec/features/process_a_request_nomis_disabled_spec.rb
  spec/features/process_a_request_reject_spec.rb
  spec/features/process_a_request_unprocessable_spec.rb
  spec/services/book_to_nomis_config_spec.rb
  spec/services/nomis/feature_spec.rb
  spec/services/staff_nomis_checker_spec.rb
Labels: review me

#1513 Use static GA cookie for visit request tracking
  app/services/ga_tracker.rb
  spec/services/ga_tracker_spec.rb
Labels: review me

#1525 Change feedback link to banner
  app/assets/stylesheets/_helpers.scss
  app/assets/stylesheets/_navigation.scss
  app/views/layouts/application.html.erb
  app/views/staff_info/show.html.erb
  config/locales/en/prison_views.yml
Labels: review me

#1523 Update CWI-channings-wood.yml
  db/seeds/prisons/CWI-channings-wood.yml
Labels: Ready For Merge, review me, slot updates

#1530 Slot update to Haverigg
  db/seeds/prisons/HVI-haverigg.yml
Labels: Ready For Merge, review me, slot updates

#1526 Staff info pages sidebar
  app/views/application/_navigation.html.erb
  app/views/prison/feedbacks/new.html.erb
Labels: Ready For Merge, review me

#1531 Remove 'iep_level_enabled' feature flag
  app/services/nomis/feature.rb
  app/services/nomis/offender.rb
  app/views/prison/visits/_prisoner_details.html.erb
  config/application.rb
  spec/decorators/visitor_decorator_spec.rb
  spec/features/process_a_request_accept_with_contact_list_spec.rb
  spec/features/process_a_request_nomis_disabled_spec.rb
  spec/features/process_a_request_reject_spec.rb
  spec/features/process_a_request_unprocessable_spec.rb
  spec/services/nomis/feature_spec.rb
Labels: review me

#1529 Remove STAFF_PRISONER_AVAILABILITY_ENABLED flag
  app/decorators/concrete_slot_decorator.rb
  app/services/book_to_nomis_config.rb
  app/services/nomis/feature.rb
  app/services/staff_nomis_checker.rb
  config/application.rb
  spec/decorators/concrete_slot_decorator_spec.rb
  spec/features/cancel_booked_to_nomis_visit_spec.rb
  spec/features/process_a_request_accept_with_contact_list_spec.rb
  spec/features/process_a_request_nomis_disabled_spec.rb
  spec/features/process_a_request_unprocessable_spec.rb
  spec/services/book_to_nomis_config_spec.rb
  spec/services/nomis/feature_spec.rb
  spec/services/staff_nomis_checker_spec.rb
Labels: Ready For Merge

#1533 Remove 'sentence_status_enabled' feature flag
  app/services/nomis/feature.rb
  app/views/prison/visits/_prisoner_details.html.erb
  config/application.rb
  spec/features/process_a_request_accept_with_contact_list_spec.rb
  spec/features/process_a_request_nomis_disabled_spec.rb
  spec/services/nomis/feature_spec.rb
Labels: review me

#1535 Remove PUBLIC_PRISONER_AVAILABILITY_ENABLED flag
  app/models/api_slot_availability.rb
  app/services/slot_availability.rb
  config/application.rb
  spec/models/api_slot_availability_spec.rb
  spec/services/slot_availability_spec.rb
  spec/support/helpers/service_helpers.rb
Labels: review me

#1536 Remove 'public_prisoner_check_enabled' feature flag
  app/services/api_prisoner_checker.rb
  config/application.rb
  spec/controllers/api/validations_controller_spec.rb
  spec/services/api_prisoner_checker_spec.rb
Labels: review me

#1544 Durham easter slot update
  db/seeds/prisons/DMI-durham.yml
Labels: Ready For Merge, review me, slot updates

#1545 Foston Hall slot updates
  db/seeds/prisons/FHI-foston-hall.yml
Labels: Ready For Merge, review me, slot updates

#1546 Pentonville slot updates
  db/seeds/prisons/PVI-pentonville.yml
Labels: Ready For Merge, review me, slot updates

#1547 New Hall slot updates
  db/seeds/prisons/NHI-new-hall.yml
Labels: Ready For Merge, review me, slot updates

#1550 Stoke Heath slot updates
  db/seeds/prisons/SHI-stoke-heath.yml
Labels: Ready For Merge, review me, slot updates

#1551 Styal slot updates
  db/seeds/prisons/STI-styal.yml
Labels: Ready For Merge, review me, slot updates

#1552 Low Newton slot updates
  db/seeds/prisons/LNI-low-newton.yml
Labels: Ready For Merge, review me, slot updates

#1548 Send slot updates
  db/seeds/prisons/SDI-send.yml
Labels: Ready For Merge, review me, slot updates

#1554 Correctly display prisoner restrictions error message
  app/services/staff_nomis_checker.rb
  spec/services/staff_nomis_checker_spec.rb
Labels: review me

#1502 Optimise librarry caching
  .circleci/config.yml
Labels: Ready For Merge

#1557 Feltham 18-21 slot update
  db/seeds/prisons/FMI-feltham-young-adults-18-21-only.yml
Labels: Ready For Merge, review me, slot updates

#1561 Update CreateNomisVisit to reflect api changes
  app/services/create_nomis_visit.rb
  spec/services/create_nomis_visit_spec.rb
  spec/services/nomis/api_spec.rb
Labels: review me

#1562 Lindholme slot update
  Gemfile.lock
  db/seeds/prisons/LHI-lindholme.yml
Labels: Ready For Merge, review me, slot updates

#1568 Holme-House-slot-updates
  db/seeds/prisons/HHI-holme-house.yml
Labels: Ready For Merge, review me, slot updates

#1572 Holme House slot update
  db/seeds/prisons/HHI-holme-house.yml
Labels: Ready For Merge, review me, slot updates

#1571 Risley slot updates
  db/seeds/prisons/RSI-risley.yml
Labels: Ready For Merge, review me, slot updates

#1576 Bullingdon remand slot updates
  db/seeds/prisons/BNI-bullingdon-remand-only.yml
Labels: Ready For Merge, review me, slot updates

#1575 Bullingdon convicted slot updates
  db/seeds/prisons/BNI-bullingdon-convicted-only.yml
Labels: Ready For Merge, review me, slot updates
