Repository ministryofjustice/prison-visits-2, pull requests merged in 2018-02, with the labels that each got.

#1368 Add Eastwood Park to APVU (DO NOT MERGE UNTIL 12/2/18)
  db/seeds/estates.yml
Labels: Do Not Merge

#1443 Holme-house-slot-updates
  db/seeds/prisons/HHI-holme-house.yml
Labels: Ready For Merge, review me, slot updates

#1442 Chelmsford-slot-updates
  db/seeds/prisons/CDI-chelmsford.yml
Labels: Ready For Merge, review me, slot updates

#1446 Swaleside-slot-updates
  db/seeds/prisons/SLI-swaleside.yml
Labels: Ready For Merge, review me, slot updates

#1445 Cardiff-slot-availability
  db/seeds/prisons/CFI-cardiff.yml
Labels: Ready For Merge, review me, slot updates

#1444 Lindholme-slot-updates
  db/seeds/prisons/LHI-lindholme.yml
Labels: Ready For Merge, review me, slot updates

#1449 North-sea-camp-slot-updates
  db/seeds/prisons/NSI-north-sea-camp.yml
Labels: Ready For Merge, review me, slot updates

#1374 Add Foston Hall to APVU Group (DO NOT MERGE UNTIL 19/2/18)
  db/seeds/estates.yml
Labels: Do Not Merge

#1451 Belmarsh-slot-updates
  db/seeds/prisons/BAI-belmarsh.yml
Labels: Ready For Merge, review me, slot updates

#1452 Holme-House-slot-updates
  db/seeds/prisons/HHI-holme-house.yml
Labels: Ready For Merge, review me, slot updates

#1456 Hewell slot updates
  db/seeds/prisons/HEI-hewell.yml
Labels: Ready For Merge, review me, slot updates

#1457 Brinsford slot updates
  db/seeds/prisons/BSI-brinsford.yml
Labels: Ready For Merge, review me, slot updates

#1459 Send slot updates
  db/seeds/prisons/SDI-send.yml
Labels: Ready For Merge, review me, slot updates

#1468 Wandsworth slot updates
  db/seeds/prisons/WWI-wandsworth.yml
Labels: Ready For Merge, review me, slot updates

#1466 Fix prisoner details validation when location API call fails
  app/decorators/visit_decorator.rb
  app/presenters/prisoner_details_presenter.rb
  app/views/prison/visits/_prisoner_details.html.erb
  spec/presenters/prisoner_details_presenter_spec.rb
Labels: bug, review me

#1474 Chelmsford slot updates
  db/seeds/prisons/CDI-chelmsford.yml
Labels: Ready For Merge, review me, slot updates

#1475 Update Risley slots
  db/seeds/prisons/RSI-risley.yml
Labels: Ready For Merge, review me, slot updates

#1467 Aylesbury-slot-updates
  db/seeds/prisons/AYI-aylesbury.yml
Labels: Ready For Merge, review me, slot updates
