Repository ministryofjustice/prison-visits-2, pull requests merged in 2018-05, with the labels that each got.

#1649 Wymott unbookable dates
  db/seeds/prisons/WMI-wymott.yml
Labels: Ready For Merge, review me, slot updates

#1638 bullet proof visit show for unknown offender number
  app/services/nomis/client.rb
  app/services/nomis/null_offender.rb
  lib/excon/middleware/custom_idempotent.rb
  spec/features/nomis_disabled_spec.rb
  spec/fixtures/vcr_cassettes/nomis_disabled_invalid_prisoner_number.yml
  spec/services/nomis/client_spec.rb
  spec/services/nomis/null_offender_spec.rb
Labels: review me

#1651 Channings Wood unbookable dates
  db/seeds/prisons/CWI-channings-wood.yml
Labels: Ready For Merge, review me, slot updates

#1661 Holme House visit slot updates
  db/seeds/prisons/HHI-holme-house.yml
Labels: Ready For Merge, review me, slot updates

#1660 Lancaster Farms visit slot updates
  db/seeds/prisons/LFI-lancaster-farms.yml
Labels: Ready For Merge, review me, slot updates

#1671 Add tracking for cancelled and withdrawn visits
  app/controllers/api/visits_controller.rb
  app/controllers/prison/cancellations_controller.rb
  app/services/ga_tracker.rb
  spec/controllers/api/visits_controller_spec.rb
  spec/controllers/prison/cancellations_controller_spec.rb
  spec/features/cancel_booked_to_nomis_visit_spec.rb
  spec/features/dashboard_spec.rb
  spec/fixtures/vcr_cassettes/cancel_visit_ga.yml
  spec/fixtures/vcr_cassettes/cancelled_visit_event.yml
  spec/fixtures/vcr_cassettes/multiple_cancellation_reasons.yml
  spec/fixtures/vcr_cassettes/withdrawn_visit_event.yml
  spec/services/ga_tracker_spec.rb
Labels: Do Not Merge, in progress

#1678 Buckley Hall unbookable date
  db/seeds/prisons/BCI-buckley-hall.yml
Labels: Ready For Merge, review me, slot updates

#1684 Update access to prison visits bookings
  db/seeds/estates.yml
Labels: in progress

#1685 fix bundler
  bin/bundle
Labels: in progress

#1686 Fix bundler
  bin/bundle
Labels: in progress

#1687 use binstub rake
  Dockerfile
Labels: in progress

#1691 Use binstubs for puma and sidekiq
  bin/puma
  bin/pumactl
  bin/sidekiq
  bin/sidekiqctl
  run-sidekiq.sh
  run.sh
Labels: in progress

#1683 Remove 'group' column from Estates table
  app/services/estate_seeder/seed_entry.rb
  db/migrate/20180521133256_remove_group_from_estates.rb
  db/schema.rb
  docs/prison_data.md
Labels: in progress

#1696 Switch from ActiveRecord::Base to ApplicationRecord
  app/models/application_record.rb
  app/models/cancellation.rb
  app/models/cancellation/reason.rb
  app/models/estate.rb
  app/models/feedback_submission.rb
  app/models/message.rb
  app/models/percentiles_by_calendar_date.rb
  app/models/percentiles_by_prison_and_calendar_date.rb
  app/models/prison.rb
  app/models/prisoner.rb
  app/models/rejection.rb
  app/models/rejection/reason.rb
  app/models/rejection_percentage_by_day.rb
  app/models/user.rb
  app/models/visit.rb
  app/models/visit_counts_by_prison_state_date_and_timely.rb
  app/models/visit_state_change.rb
  app/models/visitor.rb
Labels: in progress

#1676 Record NOMIS visit id and store VO type
  app/controllers/concerns/staff_response_context.rb
  app/models/visit.rb
  app/models/visit_order.rb
  app/models/visit_order/priviledged.rb
  app/models/visit_order/unsupported.rb
  app/services/booking_responder/accept.rb
  app/services/create_nomis_visit.rb
  app/services/nomis/booking.rb
  app/services/nomis/code.rb
  app/services/nomis/contact/contact_type.rb
  app/services/nomis/contact/gender.rb
  app/services/nomis/contact/relationship.rb
  app/services/nomis/establishment.rb
  app/services/nomis/restriction/type.rb
  app/services/nomis/visit_order.rb
  config/initializers/types.rb
  db/migrate/20180517112250_create_visit_orders.rb
  db/schema.rb
  lib/types/visit_order_type.rb
  spec/features/cancel_booked_to_nomis_visit_spec.rb
  spec/features/process_a_request_accept_with_contact_list_spec.rb
  spec/fixtures/vcr_cassettes/accept_book_to_nomis_enabled.yml
  spec/fixtures/vcr_cassettes/book_to_nomis.yml
  spec/fixtures/vcr_cassettes/cancel_to_nomis.yml
  spec/models/visit_order_spec.rb
  spec/models/visit_spec.rb
  spec/services/booking_responder/accept_spec.rb
  spec/services/create_nomis_visit_spec.rb
  spec/services/nomis/api_spec.rb
  spec/services/nomis/booking_spec.rb
  spec/types/visit_order_type_spec.rb
Labels: in progress, review me

#1697 Fix migration
  db/schema.rb
Labels: in progress

#1698 Fix visit order migratiobn
  db/migrate/20180517112250_create_visit_orders.rb
Labels: in progress

#1699 Allow prisoner with banned restriction to receive visits
  app/services/nomis/prisoner_date_availability.rb
  spec/models/prisoner_availability_validation_spec.rb
  spec/services/nomis/prisoner_date_availability_spec.rb
  spec/services/nomis/prisoner_detailed_availability_spec.rb
Labels: review me
