Repository ministryofjustice/prison-visits-2, pull requests merged in 2018-07, with the labels that each got.

#1739 Fix download CSV issue
  app/controllers/prison/print_visits_controller.rb
  app/models/print_visits.rb
  app/views/prison/print_visits/_visit_date.html.erb
  app/views/prison/print_visits/show.html.erb
  config/locales/en/prison_views.yml
  config/routes.rb
  spec/controllers/prison/print_visits_controller_spec.rb
Labels: Ready For Merge

#1749 Wymott unbookable slot update
  db/seeds/prisons/WMI-wymott.yml
Labels: Ready For Merge, review me, slot updates

#1763 Wymott unbookable slot
  db/seeds/prisons/WMI-wymott.yml
Labels: Ready For Merge, review me, slot updates

#1766 Fix sentry CSP error
  config/initializers/content_security_policy.rb
Labels: bug, review me

#1762 Remove Book To Nomis code
  app/assets/javascripts/application.js
  app/assets/javascripts/modules/moj.BookToNomis.js
  app/assets/javascripts/modules/moj.Rejection.js
  app/assets/javascripts/modules/moj.closedRestriction.js
  app/assets/javascripts/modules/moj.matchVisitors.js
  app/controllers/concerns/staff_response_context.rb
  app/controllers/prison/cancellations_controller.rb
  app/controllers/prison/visits_controller.rb
  app/models/visit_order.rb
  app/models/visit_order/priviledged.rb
  app/models/visit_order/unsupported.rb
  app/services/book_to_nomis_config.rb
  app/services/booking_responder.rb
  app/services/booking_responder/accept.rb
  app/services/booking_responder/cancel.rb
  app/services/booking_response.rb
  app/services/cancel_nomis_visit.rb
  app/services/cancellation_response.rb
  app/services/create_nomis_visit.rb
  app/services/nomis/api.rb
  app/services/nomis/booking.rb
  app/services/nomis/client.rb
  app/services/nomis/feature.rb
  app/services/persist_to_nomis_response.rb
  app/views/prison/visits/_book_to_nomis_opt_in.html.erb
  app/views/prison/visits/_cancel_visit.html.erb
  app/views/prison/visits/_requested.html.erb
  app/views/prison/visits/_visit_date_section.html.erb
  config/application.rb
  config/locales/en/prison_views.yml
  db/schema.rb
  docs/configuration.md
  spec/controllers/prison/cancellations_controller_spec.rb
  spec/controllers/prison/visits_controller_spec.rb
  spec/features/cancel_booked_to_nomis_visit_spec.rb
  spec/features/process_a_request_accept_with_contact_list_spec.rb
  spec/features/process_a_request_nomis_disabled_spec.rb
  spec/features/process_a_request_unprocessable_spec.rb
  spec/fixtures/vcr_cassettes/accept_book_to_nomis_enabled.yml
  spec/fixtures/vcr_cassettes/book_to_nomis.yml
  spec/fixtures/vcr_cassettes/book_to_nomis_duplicate.yml
  spec/fixtures/vcr_cassettes/booked_with_nomis_visit_event.yml
  spec/fixtures/vcr_cassettes/cancel_to_nomis.yml
  spec/fixtures/vcr_cassettes/opt_out_of_book_to_nomis.yml
  spec/fixtures/vcr_cassettes/process_happy_path.yml
  spec/javascripts/fixtures/process_form.html
  spec/javascripts/moj.BookToNomis_spec.js
  spec/javascripts/moj.Rejection_spec.js
  spec/services/book_to_nomis_config_spec.rb
  spec/services/booking_responder/accept_spec.rb
  spec/services/booking_responder/cancel_spec.rb
  spec/services/booking_responder_spec.rb
  spec/services/booking_response_spec.rb
  spec/services/cancel_nomis_visit_spec.rb
  spec/services/cancellation_response_spec.rb
  spec/services/create_nomis_visit_spec.rb
  spec/services/ga_tracker_spec.rb
  spec/services/nomis/api_spec.rb
  spec/services/nomis/booking_spec.rb
  spec/services/nomis/feature_spec.rb
Labels: review me

#1771 Cardiff-slot-updates
  db/seeds/prisons/CFI-cardiff.yml
Labels: Ready For Merge, review me, slot updates

#1773 Fix print visits feature spec
  spec/features/print_visits_spec.rb
Labels: review me

#1776 Remove 'prisoner banned' checkbox
  app/decorators/rejection_decorator.rb
  app/models/prisoner_availability_validation.rb
  app/models/rejection.rb
  app/services/nomis/prisoner_date_availability.rb
  app/services/staff_nomis_checker.rb
  app/views/prison/visits/_rejection_nomis.html.erb
  config/locales/en/prison_views.yml
  spec/decorators/concrete_slot_decorator_spec.rb
  spec/decorators/rejection_decorator_spec.rb
  spec/features/process_a_request_reject_spec.rb
  spec/models/metrics/rejection_percentage_spec.rb
  spec/models/prisoner_availability_validation_spec.rb
  spec/models/rejection/reason_spec.rb
  spec/presenters/graph_metrics_presenter_spec.rb
  spec/services/nomis/prisoner_date_availability_spec.rb
  spec/services/nomis/prisoner_detailed_availability_spec.rb
  spec/services/staff_nomis_checker_spec.rb
Labels: review me
