Repository ministryofjustice/prison-visits-2, pull requests merged in 2018-10, with the labels that each got.

#1841 Clean up Zendesk public inbox
  app/services/zendesk/pvb_api.rb
  lib/tasks/zendesk_cleanup.rake
  spec/services/zendesk/pvb_api_spec.rb
Labels: Ready For Merge

#1825 Permanently update Dartmoor slots - MERGE AFTER 30/9/18
  db/seeds/prisons/DAI-dartmoor.yml
Labels: Do Not Merge

#1846 New unbookable date for HMP Coldingley
  db/seeds/prisons/CLI-coldingley.yml
Labels: Ready For Merge, review me, slot updates

#1847 Add unbookable dates for HMP Haverigg
  db/seeds/prisons/HVI-haverigg.yml
Labels: Ready For Merge, review me, slot updates

#1856 Leeds Christmas slots
  db/seeds/prisons/LEI-leeds.yml
Labels: Ready For Merge, review me, slot updates

#1855 Wandsworth Christmas dates
  db/seeds/prisons/WWI-wandsworth.yml
Labels: Ready For Merge, review me, slot updates

#1860 HMP Isle of Wight Christmas dates
  db/seeds/prisons/IWI-isle-of-wight-parkhurst.yml
Labels: Ready For Merge, review me, slot updates

#1861 Bullingdon Convicted Christmas dates
  db/seeds/prisons/BNI-bullingdon-convicted-only.yml
Labels: Ready For Merge, review me, slot updates

#1862 Bullingdon Remand Christmas dates
  db/seeds/prisons/BNI-bullingdon-remand-only.yml
Labels: Ready For Merge, review me, slot updates

#1863 Swansea Christmas dates
  db/seeds/prisons/SWI-swansea.yml
Labels: Ready For Merge, review me, slot updates

#1865 Lancaster Farms Christmas slots
  db/seeds/prisons/LFI-lancaster-farms.yml
Labels: Ready For Merge, review me, slot updates

#1864 Haverigg Christmas slots
  db/seeds/prisons/HVI-haverigg.yml
Labels: Ready For Merge, review me, slot updates

#1868 Sudbury Christmas dates
  db/seeds/prisons/SUI-sudbury.yml
Labels: Ready For Merge, review me, slot updates

#1866 Maidstone Christmas 2018 slots
  db/seeds/prisons/MSI-maidstone.yml
Labels: Ready For Merge, review me, slot updates

#1867 Portland Christmas dates
  db/seeds/prisons/PDI-portland.yml
Labels: Ready For Merge, review me, slot updates

#1872 Woodhill slot updates
  db/seeds/prisons/WHI-woodhill.yml
Labels: Ready For Merge, review me, slot updates

#1871 Stocken Christmas dates
  db/seeds/prisons/SKI-stocken.yml
Labels: Ready For Merge, review me, slot updates

#1870 Leyhill Christmas dates
  db/seeds/prisons/LYI-leyhill.yml
Labels: Ready For Merge, review me, slot updates

#1869 Liverpool social Christmas dates
  db/seeds/prisons/LPI-liverpool-social-visits.yml
Labels: Ready For Merge, review me, slot updates

#1874 Lindholme Christmas dates
  db/seeds/prisons/LHI-lindholme.yml
Labels: Ready For Merge, review me, slot updates

#1876 Coldingley slot update
  db/seeds/prisons/CLI-coldingley.yml
Labels: Ready For Merge, review me, slot updates

#1875 Channings Wood Christmas slots
  db/seeds/prisons/CWI-channings-wood.yml
Labels: Ready For Merge, review me, slot updates

#1877 Send Christmas dates
  db/seeds/prisons/SDI-send.yml
Labels: Ready For Merge, review me, slot updates

#1878 Wealstun Christmas dates
  db/seeds/prisons/WEI-wealstun.yml
Labels: Ready For Merge, review me, slot updates

#1879 Wetherby Christmas dates
  db/seeds/prisons/WYI-wetherby.yml
Labels: Ready For Merge, review me, slot updates

#1880 Add unbookable date to HMP Wymott
  db/seeds/prisons/WMI-wymott.yml
Labels: Ready For Merge, review me, slot updates

#1881 Exeter Christmas dates
  db/seeds/prisons/EXI-exeter.yml
Labels: Ready For Merge, review me, slot updates

#1886 Buckley Hall Christmas visit dates
  db/seeds/prisons/BCI-buckley-hall.yml
Labels: Ready For Merge, review me, slot updates

#1885 Wymott Christmas visit dates
  db/seeds/prisons/WMI-wymott.yml
Labels: Ready For Merge, review me, slot updates

#1884 Thorn Cross Christmas visit dates
  db/seeds/prisons/TCI-thorn-cross.yml
Labels: Ready For Merge, review me, slot updates

#1883 Hindley Christmas visit dates
  db/seeds/prisons/HII-hindley.yml
Labels: Ready For Merge, review me, slot updates

#1896 Chelmsford Christmas visit dates
  db/seeds/prisons/CDI-chelmsford.yml
Labels: Ready For Merge, review me, slot updates

#1906 Channings Wood Christmas visit slots
  db/seeds/prisons/CWI-channings-wood.yml
Labels: Ready For Merge, review me, slot updates

#1907 Durham Christmas visit slots
  db/seeds/prisons/DMI-durham.yml
Labels: Ready For Merge, review me, slot updates

#1909 Medway Christmas visit slots
  db/seeds/prisons/MWI-medway.yml
Labels: Ready For Merge, review me, slot updates

#1910 Warren Hill Christmas visit slots
  db/seeds/prisons/WII-warren-hill.yml
Labels: Ready For Merge, review me, slot updates

#1911 Wayland Christmas visit slots
  db/seeds/prisons/WLI-wayland.yml
Labels: Ready For Merge, review me, slot updates

#1912 Winchester Convicted Christmas visit slots
  db/seeds/prisons/WCI-winchester-convicted-only.yml
Labels: Ready For Merge, review me, slot updates

#1913 Winchester Remand Christmas visit slots
  db/seeds/prisons/WCI-winchester-remand-only.yml
Labels: Ready For Merge, review me, slot updates

#1914 Wealstun slot updates
  db/seeds/prisons/WEI-wealstun.yml
Labels: Ready For Merge, review me, slot updates

#1916 Gartree Christmas dates removal
  db/seeds/prisons/GTI-gartree.yml
Labels: Ready For Merge, review me, slot updates

#1917 Leicester Christmas visit slots
  db/seeds/prisons/LCI-leicester.yml
Labels: Ready For Merge, review me, slot updates
